import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

import feedbackService from '../../services/feedbackService.js';
import StatCard from '../../components/StatCard.jsx';
import EmptyState from '../../components/EmptyState.jsx';
import EventStatusBadge from '../../components/EventStatusBadge.jsx';
import StarRating from '../../components/feedback/StarRating.jsx';
import SentimentBadge from '../../components/feedback/SentimentBadge.jsx';
import ErrorBanner from '../../components/ui/ErrorBanner.jsx';
import Icon from '../../components/ui/Icon.jsx';
import { formatDateTime } from '../../utils/eventMeta.js';

/** /organiser/events/:id/feedback — participant feedback + sentiment for an owned event. */
const OrganiserEventFeedback = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loadState, setLoadState] = useState('loading');
  const [error, setError] = useState('');

  const load = useCallback(() => {
    setLoadState('loading');
    feedbackService
      .listForEvent(id)
      .then((res) => {
        setData(res);
        setLoadState('ready');
      })
      .catch((err) => {
        if (err.status === 401) {
          navigate('/login', { replace: true });
          return;
        }
        setError(
          err.status === 403
            ? 'You can only view feedback for your own events.'
            : err.status === 404
              ? 'Event not found.'
              : err.message || 'Unable to load feedback. Please try again.',
        );
        setLoadState('error');
      });
  }, [id, navigate]);

  useEffect(() => load(), [load]);

  if (loadState === 'loading') return <div className="h-64 animate-pulse rounded-lg bg-slate-100" />;
  if (loadState === 'error') {
    return (
      <div className="space-y-3">
        <ErrorBanner message={error} />
        <Link to="/organiser/events" className="text-sm font-medium text-indigo-600 hover:underline">
          Back to My Events
        </Link>
      </div>
    );
  }

  const { event, summary, feedback } = data;

  return (
    <section className="space-y-6">
      <div>
        <Link to={`/organiser/events/${id}`} className="text-xs font-medium text-indigo-600 hover:underline">
          ← Event details
        </Link>
        <div className="mt-1 flex flex-wrap items-center gap-3">
          <h1 className="text-xl font-bold text-slate-900">{event.title}</h1>
          <EventStatusBadge status={event.status} />
        </div>
        <p className="mt-1 text-sm text-slate-500">
          What participants said about this event, with AI sentiment on each comment.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
        <StatCard label="Responses" value={summary.total} accent="indigo" icon="message-square" />
        <StatCard label="Positive" value={summary.positive} accent="emerald" icon="thumbs-up" />
        <StatCard label="Neutral" value={summary.neutral} accent="slate" icon="message-square" />
        <StatCard label="Negative" value={summary.negative} accent="rose" icon="alert-circle" />
        <StatCard
          label="Avg rating"
          value={summary.averageRating != null ? `${summary.averageRating} / 5` : '—'}
          accent="amber"
          icon="star"
        />
      </div>

      <p className="flex items-center gap-1.5 text-xs text-slate-400">
        <Icon name="sparkles" className="h-3.5 w-3.5 shrink-0 text-violet-400" />
        Sentiment (Positive / Neutral / Negative) is generated by an AI model from each comment — a signal to help
        you scan feedback quickly, not an exact measurement.
      </p>

      {summary.unanalysed > 0 && (
        <p className="flex items-center gap-2 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
          <Icon name="alert-triangle" className="h-4 w-4 shrink-0" />
          {summary.unanalysed} comment{summary.unanalysed === 1 ? '' : 's'} could not be analysed for sentiment
          (the AI service was unavailable at submission time). The feedback itself is recorded.
        </p>
      )}

      {feedback.length === 0 ? (
        <EmptyState
          title="No feedback yet"
          description={
            event.status === 'COMPLETED'
              ? 'None of the participants who attended have submitted feedback yet.'
              : 'Feedback opens to participants once this event is marked completed.'
          }
          icon="message-square"
        />
      ) : (
        <ul className="space-y-3">
          {feedback.map((f) => (
            <li key={f.id} className="rounded-lg border border-slate-200 bg-white p-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="font-medium text-slate-900">{f.participant?.name ?? 'Participant'}</span>
                  <StarRating value={f.rating} readOnly size="sm" />
                </div>
                {f.comment ? (
                  <SentimentBadge sentiment={f.sentiment} status={f.sentimentStatus} score={f.sentimentScore} />
                ) : (
                  <span className="text-xs text-slate-400">Rating only</span>
                )}
              </div>
              {f.comment && (
                <p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{f.comment}</p>
              )}
              <p className="mt-2 text-xs text-slate-400">
                {formatDateTime(f.submittedAt)}
                {f.updatedAt && f.updatedAt !== f.submittedAt ? ' · edited' : ''}
              </p>
            </li>
          ))}
        </ul>
      )}
    </section>
  );
};

export default OrganiserEventFeedback;
